.PHONY: clean All

All:
	@echo "----------Building project:[ Time - Debug ]----------"
	@"$(MAKE)" -f  "Time.mk"
clean:
	@echo "----------Cleaning project:[ Time - Debug ]----------"
	@"$(MAKE)" -f  "Time.mk" clean
